# Generated by Django 5.1 on 2024-08-13 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=100)),
                ("driver_name", models.CharField(max_length=100)),
                ("capacity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("availability_status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_id", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField(blank=True, null=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.vehicle",
                    ),
                ),
            ],
        ),
    ]
